usethis::use_package_doc()
devtools::document()
if(file.exists("DESCRIPTION")) unlink("docs", recursive = TRUE)
codemetar::write_codemeta()
knitr::knit("README.Rmd")
pkgdown::build_site()
devtools::check()
